const checkUserAuthentication = (val: number) => {
  return 2;
};

export enum authenticationEnum {
  Super_Admin = 1,
  Home = 2,
  Home_Dashboard = 3,
  Auth = 4,
  Auth_Login = 5,
  Auth_Register = 6,
  Privileges = 7,
  System_Privileges = 8,
  Privilege_Groups = 9,
  Users = 10,
  Test = 11,
  FormDemo = 12,
  Employee = 13,
  Employee_Login = 14,
  Customer = 15,
  Item = 16,
  Task_Assign = 17,
  All_Tasks = 18,
  Supplier = 19,
  Task_Introduce = 20,
  User_Profile = 21,
  Online_Products = 22,
  GRN = 23,
  Attendance = 24,
  Employee_List_Report = 25,
  Customer_Feedback = 26,
  Online_Shopping = 27,
  All_Feedbacks = 28,
  Vehicles = 30,
  Additional_Services = 31,
  Appointment_List = 32,
  All_Appointments = 33,
}
